// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectAmanda.Models;

#nullable disable

namespace ProjectAmanda.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220123030418_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("ProjectAmanda.Models.Store", b =>
                {
                    b.Property<int>("storeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("storeId");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("ProjectAmanda.Models.StoreItem", b =>
                {
                    b.Property<int>("storeItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("completed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("selected")
                        .HasColumnType("INTEGER");

                    b.Property<int>("storeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("storeItemId");

                    b.HasIndex("storeId");

                    b.ToTable("StoreItems");
                });

            modelBuilder.Entity("ProjectAmanda.Models.StoreItem", b =>
                {
                    b.HasOne("ProjectAmanda.Models.Store", null)
                        .WithMany("items")
                        .HasForeignKey("storeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectAmanda.Models.Store", b =>
                {
                    b.Navigation("items");
                });
#pragma warning restore 612, 618
        }
    }
}
